name: Auto Post to X

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run poster
        run: npm start
        env:
          X_USERNAME: ${{ secrets.X_USERNAME }}
          X_PASSWORD: ${{ secrets.X_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
